
TEMPLATE_DATA_DIR = /data/projects/UVMCodeGen/examples/transaction_class/
TRANS_DATA = sequence_item_template.data
TRANS_HDR_TEMPLATE = sequence_item_header_template.mako
TRANS_IMPL_TEMPLATE = sequence_item_implementation_template.mako

include ../make.rules

