
TEMPLATE_DATA_DIR = /data/projects/UVMCodeGen/examples/driver_class/
TRANS_DATA = sequence_driver_template.data
TRANS_HDR_TEMPLATE = sequence_driver_header_template.mako
TRANS_IMPL_TEMPLATE = sequence_driver_implementation_template.mako

include ../make.rules

